spring:
  profiles:
    active: dev  # 기본적으로 dev 환경임을 명시
  output:
    ansi:
      enabled: always  # 콘솔 색상 변경
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/  # 타임리프 캐시 끄기(이 설정 해야 꺼짐)
    devtools:
      livereload:
        enabled: true
      restart:
        enable: true
  datasource:
    url: jdbc:mariadb://mariadb.mypc.myvbox:3306/tutorial1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 옵션: none, validate, update, create, create-drop
    properties:
      hibernate:
        show_sql: true # 실행되는 SQL 쿼리 확인
        format_sql: true  # 출력되는 SQL을 포맷팅
        use_sql_comments: true